name: CI Example

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Echo a message
      run: echo "Chào mừng đến với GitHub Actions! Đã đẩy mã nguồn lên nhánh master."
